name: Build arter97 Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      kpm_support:
        description: 'Enable KPM support'
        required: false
        type: boolean
        default: true
      susfs_support:
        description: 'Enable SUSFS support'
        required: false
        type: boolean
        default: true
      bbg_support:
        description: 'Enable BBG support'
        required: false
        type: boolean
        default: true
      susfs_force:
        description: 'Force SUSFS patch apply (ignore failures)'
        required: false
        type: boolean
        default: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      kernel_repo: https://github.com/arter97/android_kernel_nothing_sm8475
      kernel_branch: master
      kernel_defconfig: /defconfig
      extra_configs: ''
      susfs_branch: gki-android12-5.10
      extra_patches_dir: patches/arter97
      kpm_support: ${{ inputs.kpm_support }}
      susfs_support: ${{ inputs.susfs_support }}
      susfs_force: ${{ inputs.susfs_force }}
      bbg_support: ${{ inputs.bbg_support }}
