name: Test All Builds

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-default:
    name: Build (LineageOS)
    uses: ./.github/workflows/build.yml
    with:
      kernel_type: LineageOS
      kpm_support: true
      susfs_support: true
      bbg_support: true
      susfs_force: false

  build-nothingoss:
    name: Build (NothingOSS)
    uses: ./.github/workflows/build.yml
    with:
      kernel_type: NothingOSS
      kernel_repo: https://github.com/NothingOSS/android_kernel_msm-5.10_nothing_sm8475.git
      kernel_branch: sm8475/b/mr
      kernel_defconfig: gki_defconfig
      extra_configs: vendor/waipio_GKI.config
      susfs_branch: gki-android13-5.10
      kpm_support: true
      susfs_support: true
      susfs_force: false
      bbg_support: true

  build-arter97:
    name: Build (arter97)
    uses: ./.github/workflows/build.yml
    with:
      kernel_type: arter97
      kernel_repo: https://github.com/arter97/android_kernel_nothing_sm8475
      kernel_branch: master
      kernel_defconfig: /defconfig
      extra_configs: ''
      susfs_branch: gki-android13-5.10
      extra_patches_dir: patches/arter97
      kpm_support: true
      susfs_support: true
      susfs_force: false
      bbg_support: true
